services:
  secret-vault-backend:
    container_name: "secret-vault-backend"
    build: .
    working_dir: /
    command: uvicorn src.main:app --host 0.0.0.0  --reload --port 8000
    environment:
      DEBUG: 1
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure